<template>
  <div class="chapi-handler">
    <p>
      Want to try the new CHAPI integration? Click
      <!-- <a :href="'/' + type + '/chapi/' + token">here!</a> -->
      <a href="#" @click="onClick">here!</a>
    </p>
  </div>
</template>

<script lang="ts">
import * as CredentialHandlerPolyfill from "credential-handler-polyfill";
import axios from "axios";

const WAIT_TIME = 200;

type VerifiablePresentation = {};
type WebCredential = {
  type: string;
  dataType: string;
  data: VerifiablePresentation;

  options: {
    recommendedHandlerOrigins: string[];
    protocols: any;
  };
};

export default {
  name: "ChapiHandler",
  props: {
    requestId: {
      type: String,
      required: true,
    },
    token: {
      type: String,
      required: true,
    },
    type: {
      type: String,
      required: true,
      validator: (value) => ["issue", "verify"].includes(value),
    },
  },
  data() {
    return {};
  },
  computed: {},
  async created() {
    await CredentialHandlerPolyfill.loadOnce();
    console.log("Successfully loaded polyfill");
  },
  methods: {
    async onClick() {
      const verifiablePresentation = {
        query: [
          {
            type: "QueryByExample",
            credentialQuery: {
              reason: "Please present your Credential.",
              // TODO: This should be generated by the backend
              example: {
                // "@context": [
                //   "https://w3id.org/credentials/v1",
                //   "https://www.w3.org/2018/credentials/examples/v1",
                // ],
                // TODO: Should be generated by the backend
                type: [
                  "VerifiableCredential",
                  "JolocomFullNameCredential",
                  "TrinsicFullNameCredential", // NOTE: Is this allowed? (is it OR or AND)
                ],
                // credentialSubject: {
                //   id: "did:example:ebfeb1f712ebc6f1c276e12ec21",
                // },
              },
            },
          },
        ],
      };

      const credentialQuery: any = {
        web: {
          VerifiablePresentation: verifiablePresentation,
        },
      };

      // We request the credential from the user through CHAPI
      const credential: WebCredential = (await navigator.credentials.get(
        credentialQuery
      )) as unknown as WebCredential;
      console.log("Result of get() request:", JSON.stringify(credential));

      // Display error on fail
      if (credential == null || credential.data == null) {
        this.$bvToast.toast(
          `Either the request was cancelled or something went
          wrong.`,
          {
            title: "No credential found",
            variant: "danger",
            autoHideDelay: 5000,
            appendToast: true,
          }
        );
      }

      // We handle the request through the backend
      try {
        const result = await axios.post(`/api/${this.type}/chapi`, credential, {
          params: {
            [`${this.type}RequestId`]: this.requestId,
          },
        });
        console.log(result.data);
        this.connectorData = result.data;
        const that = this;
        setTimeout(() => (that.status = "ready"), WAIT_TIME);
      } catch (e) {
        console.error(e);
        this.error();
      }
    },
  },
};
</script>
